#Name of workflow
name: Node CI
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
       node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: make lint
      - run: make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
      # Add code climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
